version: '3'

services:

  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./downloads:/downloads
    network_mode: "service:gluetun"
    restart: always

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      ###### Transmission Ports
      - 9091:9091
    volumes:
      - ./vpngate.ovpn:/gluetun/custom.conf
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.conf
    restart: always

  minidlna:
    image: vladgh/minidlna
    container_name: minidlna
    network_mode: "host"
    environment:
      - MINIDLNA_MEDIA_DIR=/media
      - MINIDLNA_FRIENDLY_NAME=miniDLNA
    volumes:
      - ./downloads:/media
    restart: always
