[jackett]
base_url = "http://127.0.0.1:9117"
transmission_base_url = "http://jackett:9117"
config_dir = "../jackett-config/Jackett"

[network]
timeout = 20

[paths]
downloads_root = "../downloads"
library_root = "../library"

[transmission]
rpc_url = "http://127.0.0.1:9091/transmission/rpc"
